/**
 * Design tokens for the learning magazine.
 *
 * This file is the source of truth; `tokens.css` is generated from it by
 * `pnpm --filter @lm/tokens build`, and a test fails if the two drift.
 * Components read tokens only through CSS custom properties, so an audience
 * theme is a new set of values, never a new component.
 */

export type ColorTokens = {
  bg: string;
  surface: string;
  surface2: string;
  ink: string;
  inkMuted: string;
  accent: string;
  accentInk: string;
  accentSoft: string;
  warm: string;
  warmSoft: string;
  insight: string;
  insightSoft: string;
  border: string;
  borderStrong: string;
  focus: string;
};

export type ThemeMode = "light" | "dark" | "projection";

/**
 * School theme: playful but not childish. Warm paper, deep ink, one indigo
 * accent, amber for "look here", teal for "insight". No red: a wrong guess
 * is never signalled with an alarm colour (constitution, Article 8).
 */
export const school: Record<ThemeMode, ColorTokens> = {
  light: {
    bg: "#FBF8F2",
    surface: "#FFFFFF",
    surface2: "#F2EEE6",
    ink: "#1D1B26",
    inkMuted: "#514E62",
    accent: "#4338CA",
    accentInk: "#FFFFFF",
    accentSoft: "#E6E4FB",
    warm: "#9A4A07",
    warmSoft: "#FDF0DC",
    insight: "#0B6B63",
    insightSoft: "#DDF3EF",
    border: "#E3DDD1",
    borderStrong: "#7E7868",
    focus: "#1D4ED8",
  },
  dark: {
    bg: "#16151C",
    surface: "#201F28",
    surface2: "#2A2934",
    ink: "#F3F1EC",
    inkMuted: "#BAB6C7",
    accent: "#A5B4FC",
    accentInk: "#16151C",
    accentSoft: "#2E2B52",
    warm: "#FBBF24",
    warmSoft: "#3A2E14",
    insight: "#5EEAD4",
    insightSoft: "#133B37",
    border: "#3A3846",
    borderStrong: "#8A869A",
    focus: "#93C5FD",
  },
  /** Projection: maximum contrast that survives washed-out classroom projectors. */
  projection: {
    bg: "#FFFFFF",
    surface: "#FFFFFF",
    surface2: "#F1F1F1",
    ink: "#000000",
    inkMuted: "#262626",
    accent: "#2A1FA8",
    accentInk: "#FFFFFF",
    accentSoft: "#E4E2FF",
    warm: "#7A3A00",
    warmSoft: "#FFEBCC",
    insight: "#004D46",
    insightSoft: "#D2F2EC",
    border: "#8C8C8C",
    borderStrong: "#000000",
    focus: "#B45309",
  },
};

export const space = { 1: "4px", 2: "8px", 3: "12px", 4: "16px", 5: "24px", 6: "32px", 7: "48px", 8: "64px", 9: "96px" } as const;
export const radius = { sm: "6px", md: "12px", lg: "20px", pill: "999px" } as const;
export const motion = { fast: "120ms", base: "220ms", slow: "420ms", ease: "cubic-bezier(0.2, 0.7, 0.2, 1)" } as const;
export const elevation = {
  1: "0 1px 2px rgb(20 18 30 / 0.06), 0 1px 1px rgb(20 18 30 / 0.04)",
  2: "0 6px 20px rgb(20 18 30 / 0.08), 0 2px 6px rgb(20 18 30 / 0.05)",
} as const;

/** Type scale. Personal mode is fluid; projection guarantees >= 28px body at 1080p. */
export const type = {
  personal: { body: "clamp(1.0625rem, 0.98rem + 0.35vw, 1.1875rem)", small: "0.9375rem", h3: "1.3rem", h2: "clamp(1.5rem, 1.2rem + 1.2vw, 2.1rem)", h1: "clamp(2.1rem, 1.4rem + 3vw, 3.6rem)" },
  projection: { body: "max(30px, 1.56vw)", small: "max(28px, 1.46vw)", h3: "max(34px, 1.8vw)", h2: "max(44px, 2.3vw)", h1: "max(60px, 3.2vw)" },
  /** Indic scripts need taller lines for matras and conjuncts. */
  leading: { latin: "1.55", indic: "1.8", tight: "1.2", indicTight: "1.4" },
} as const;

/** Minimum target sizes (WCAG 2.2 AA 2.5.8 asks 24px; the platform uses 44px, 64px projected). */
export const target = { personal: "44px", projection: "64px" } as const;

const kebab = (s: string) => s.replace(/[A-Z0-9]/g, (m) => `-${m.toLowerCase()}`).replace(/^-/, "");

function colorVars(c: ColorTokens): string {
  return Object.entries(c)
    .map(([k, v]) => `  --color-${kebab(k)}: ${v};`)
    .join("\n");
}

/** Renders the full stylesheet of custom properties. */
export function renderCss(): string {
  const scalar = (prefix: string, rec: Record<string | number, string>) =>
    Object.entries(rec).map(([k, v]) => `  --${prefix}-${k}: ${v};`).join("\n");
  const typeVars = (t: Record<string, string>) => Object.entries(t).map(([k, v]) => `  --text-${k}: ${v};`).join("\n");
  return `/* Generated by packages/tokens/scripts/build-css.ts. Do not edit by hand. */
:root {
  color-scheme: light;
${colorVars(school.light)}
${scalar("space", space)}
${scalar("radius", radius)}
${scalar("motion", motion)}
${scalar("elevation", elevation)}
${typeVars(type.personal)}
  --leading-body: ${type.leading.latin};
  --leading-tight: ${type.leading.tight};
  --target-min: ${target.personal};
  --measure: 38rem;
}

@media (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]) {
    color-scheme: dark;
${colorVars(school.dark).replace(/^ {2}/gm, "    ")}
  }
}

:root[data-theme="dark"] {
  color-scheme: dark;
${colorVars(school.dark)}
}

/* Classroom mode projects: high contrast, large type, big targets. Scoped to any
   element so previews can show both modes side by side; same specificity as the
   dark rules above and later in the file, so it wins over them. */
:root[data-mode="classroom"], :root [data-mode="classroom"] {
  color-scheme: light;
${colorVars(school.projection)}
${typeVars(type.projection)}
  --target-min: ${target.projection};
  --measure: 60rem;
}

:lang(hi), :lang(te), :lang(mr), :lang(ta), :lang(bn) {
  --leading-body: ${type.leading.indic};
  --leading-tight: ${type.leading.indicTight};
}

@media (prefers-reduced-motion: reduce) {
  :root {
    --motion-fast: 0ms;
    --motion-base: 0ms;
    --motion-slow: 0ms;
  }
}
`;
}
